### ISSUE TITLE
proj4leaflet not working with native crs

### ISSUE THREAD

**Issue by tim-salabim** [bhaskarvk/leaflet#15]
I have finally had a bit of time to test the new proj4leaflet integration from Bhaskar. First of all, many thanks for tackling this. This is highly needed for spatial analysis workflows.

While the Antarctica example (http://rpubs.com/bhaskarvk/leaflet-polarmaps) works, I was not able to get it to show the standard meuse SpatialPointsDataFrame from the sp package in its native projection (EPSG:28992). 

There's a couple of noteworthy issues:

1) when passing the natively projected points, they are not shown at all
2) when passing them in longlat (epsg:4326) they are shown but have issues with zooming
3) when only passing one of `code` or `proj4def` in `leafletCRS` nothing is rendered, if both are provided it seems to work

Here's the code to reproduce this:

```
# devtools::install_github("bhaskarvk/leaflet", ref = "feature/upgrade-leaflet-PR")
library(mapview) # for the popupTables
library(sp)

data(meuse)
coordinates(meuse) <- ~x+y
proj4string(meuse) <- CRS("+init=epsg:28992")
meuse_ll <- spTransform(meuse, CRS("+init=epsg:4326"))

resolutions <- c(8192, 4096, 2048, 1024, 512, 256)

## if one of code or proj4def is not provided it doesn't work
crsobj <- leafletCRS(
  crsClass = "L.Proj.CRS",
  code = 'EPSG:28992',
  proj4def = proj4string(meuse),
  resolutions = resolutions)

## does not render any points
leaflet(options = leafletOptions(crs = crsobj,
                                 minZoom = 0,
                                 maxZoom = 18)) %>%
  setView(5.734745, 50.964112, zoom = 8) %>%
  addCircleMarkers(data = meuse, popup = popupTable(meuse))

## renders points, but has issues with zoom,
## e.g. in setView zoom levels larger than 5 are identical.
## Also mouse zoomin is more than sketchy
leaflet(options = leafletOptions(crs = crsobj,
                                 minZoom = 0,
                                 maxZoom = 18)) %>%
  setView(5.734745, 50.964112, zoom = 5) %>%
  addCircleMarkers(data = meuse_ll, popup = popupTable(meuse))
```

There's a few issues I would like to raise regarding the above points:

1+2) is this a flaw in the underlying proj4leafletjs? It kinda defies the purpose of a proj4 integration if we again have to unproject to longlat first.

3) this is hopefully fixable as we quite often don't know the epsg code, we often only have the proj4 string (which is sufficient for projection definition).

**Comment by bhaskarvk** [comment]
vector data will need to be reprojected to 4326 that's a limitation of leaflet nothing proj4leaflest/proj4js can do about.
Maybe we can reproject vector data internally, something for @jcheng5 to think about. It gets even trickier w/ GeoJSON & TopoJSON.

I will checkout the zoom issue.

**Comment by mdsumner** [comment]
@tim-salabim @bhaskarvk get a set of matching EPSG and PROJ.4 codes with make_EPSG: 

```R
epsg <- tibble::as_tibble(rgdal::make_EPSG ())
```

There's a weird AsIs thing, so fix with

```R
epsg[] <- lapply(epsg, as.character)
```

That gives us an easily accessible set of EPSG codes and PROJ.4 strings that *should work*. :)

The master EPSG set is much bigger, but still it doesn't take much to want a custom projection that has no EPSG - (in PostGIS for example you are expected to add your own new code against params in the db). PROJ.4, WKT (and other commercial packages as well) provide a more general facility to define a projection, but of course the world is full of shortcuts and conventions and not everything is understood everywhere. There's a lot going on in PROJ.4 right now so that's worth keeping an eye on: 

https://github.com/OSGeo/proj.4

(I'm aware this is heaping a big topic on the discussion, and it's not an easy one but there's also no clear right answer so I guess airing as much as we each know from different directions is probably helpful. )

**Comment by tim-salabim** [comment]
@bhaskarvk Wow, that is some bad design on the leaflet side... Introducing massive overhead!

**Comment by mdsumner** [comment]
It's common though, same with KML and (in most camps) GeoJSON. Shapefiles technically are long-lat only, the spec never intended projected interchange.  This must be a topic in leaflet world?

**Comment by bhaskarvk** [comment]
@tim-salabim I checked and I think most of your issues are due to underlying leaflet and/or proj4leaflet+proj4js, and some bugs in your code ;) (although that's not your fault, the documentation needs to improve).

## Zooming issue

For the zoom issue, the length of the `resolutions` vector should be equal to `maxZoom+1-minZoom` i.e. you need to specify 1 resolution per zoom level. You specified only 5 resolutions, but your `minZoom = 0` and `maxZoom = 18`.  Hence the reason for the non-zooming past level 5.

Secondly for the jerky zoom issue, the resolution vector should be constructed carefully, and I wish  I knew what carefully meant. I just googled for leaflet + epsg28992 and found a sample for it, so I used that. Once I used that, the zooming issue was gone, i.e. you could zoom in and out smoothly from level 0 to 18.
For the curious the formula seems to be

```r
resolutions = a*(2^(maxZoom:minZoom))
```
Where a is a multiplier that seems to vary. Mostly it's 8, giving you resolutions from 256 onwards. but in this case 28992 it was 0.42.

## Leaflet needs vector data in 4326

Now as to the issue of having to reproject vector data to 4326, that's the underlying leaflet implementation. As I indicated if @jcheng5 is open to it, we may consider a reproject=T/F option to add(Markers|Poly*|geo/topoJSON) methods, which if set to T will reproject the data to 4326. But it's not a simple solution, as we work with not only SP* classes which have a proj4 string defined, but simple data frames or X/Y cols, which don't have a proj4 string. So then for such classes we will also need the user to specify the source proj4 string. Which leads me to believe that the user is better of performing this re-projection to 4326 herself.

## Example

http://rpubs.com/bhaskarvk/epsg-28992

I even got a TMS server to show up tiles behind your markers, the only issue is the TMS tiles jump when you zoom from level 9 to 10, and I don't know why that is. You can clearly see the jerky jump in the last map. Otherwise it works perfectly. If you find a better TMS provider or the reason for the jump in tiles between zoom level 9 and 10, I'll be happy to recode.

I'm closing this issue but your observations in the larger context are correct, but unfortunately outside the scope of the R package. FWIW I did find a small issue in code which I fixed, but it doesn't affect any of this.

**Comment by bhaskarvk** [comment]
The documentation aspect is now being track @ #16.

**Comment by tim-salabim** [comment]
Thanks for clearing up the zoom issue. I was expecting it to be my non-understanding of the arguments. 

As for the issue of automatically reprojecting, I would really advice against such a thing. There are many pitfalls and it should really only be used by people who understand what they are doing. E.g. there are CRSs where reprojecting to longlat will result in undefined coordinates. My take here is that if someone really wants projected maps, they should also provide suitable projected tiles and know where and what to pass to leaflet. Setting up a leaflet call as in your antarctica example is straight forward for someone who routinely works with the CRS in question.

My slight 'disappointment' is related to mapview as I was hoping to be able to use `leafletCRS` to be able to render in native crs if the user wishes to do so. But from the point of view of quick visual inspection of the data it is not acceptable to have to unproject and then have the plugin reproject to the data's original crs. This is simply too much overhead as spatial data can grow quickly to large proportions.

It is, however, awesome to have the option of a custom crs definition, as for creating a final map for publication this overhead should be acceptable.

**Comment by bhaskarvk** [comment]
Found this old issue discussing this very issue https://github.com/rstudio/leaflet/issues/139.
